#
# HP StorageWorks D2600/D2700 6GB SAS Modular Disk System Firmware
#


#
# Version 134
# Oct 3, 2011
#
# https://support.hpe.com/connect/s/softwaredetails?softwareId=MTX-92e421b977084f11979088a58e
#
CAMSPR0134_6G_app_4MB_ai.pmc:
	curl -O $@ https://downloads.hpe.com/pub/softlib2/software1/pubsw-windows/p1739937749/v72523/CAMSPR0134_6G_app_4MB_ai.pmc

#
# Version 146
# Sep 13, 2012
#
# https://support.hpe.com/connect/s/softwaredetails?softwareId=MTX_f10f40ca1ae04ef8845b79e3c6
#
CAMSPR0146_6G_app_4MB_ai.pmc:
	curl -O $@ https://downloads.hpe.com/pub/softlib2/software1/pubsw-windows/p1739937749/v80905/CAMSPR0146_6G_app_4MB_ai.pmc


